### ISSUE TITLE
Prevent variable deletion

### ISSUE THREAD

**Issue by zomars** [chempogonzalez/dotenv-checker#15]
First of all, I'm loving this tool so far. Thank you for doing this!

I wanted to ask, is there a way to prevent the script from deleting keys that aren't in the schema? I'm ok with adding new keys from schema, but sometimes we're using some variables like `NODE_ENV=production` and such and it's kinda painful to be having to restore those each time we run dev.

I know we already have the options to ask for update but that's not the desired behavior in this case.

**Comment by zomars** [comment]
Just found out that variables weren't deleted but just moved to the top. Closing this.

**Comment by chempogonzalez** [comment]
@zomars First of all, thanks so much for your comment!.

Sorry for the delayed response. Yes, as you said, the variables are not removed at all. They are just moved to the top enclosed in a "block" to be aware of the miss-synchronized keys. They are displayed in the terminal output as well.
