### ISSUE TITLE
Add an option to *not* add "predev" script.

### ISSUE THREAD

**Issue by jckw** [chempogonzalez/dotenv-checker#23]
First thing: thank you for making this library! It's so simple and useful - I use it on all of my projects now.

At the moment, dotenv-checker adds a `"predev"` script to the package.json when run (sometimes).

Many of the projects I work on now use turborepo which allow specifying "dependsOn" steps in a build pipeline. This means that I don't need to use the predev script (which would also run twice if I left it there), plus I'd prefer to keep my package.json clean.

It would be great to be able to specify something so that the predev script is _not_ added.

**Comment by jckw** [comment]
Also created a bounty on this as a tip :) 

<a href="https://until.dev/bounty/chempogonzalez/dotenv-checker/23">
  <img src="https://until.dev/api/github/chempogonzalez/dotenv-checker/23/chart.svg" alt="Current bounty reward" alt="Until bounty reward timeline" />
</a>

To make this a public bounty or have a reward split, the maintainer can reply to this comment.

**Comment by chempogonzalez** [comment]
Hi! @jckw thank you for your issue. Sorry for the delayed response.

I'm with you! I'm using turborepo too an I was planning to make it disabled by default in a new version but keeping it as an opt-in as well in case someone wants to keep it working like it's right now. I'll commit it and publish it soon for sure. I'll notify you when it's available.


Thank you!
